# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
source 'https://github.com/CocoaPods/Specs'
# Pods for DhtUnitTest
pod 'Quick'
pod 'Nimble'

target 'DhtUnitTest' do
end
target 'DhtUnitTestTests' do
end

target 'TestCaseTests' do
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = ‘3.0’
end
end
end
